package editor;

public enum ActionEditor {

	QUIT,

	EDITOR, EDIT_CUBE, EDIT_MULTI_CUBE, EDIT_MULTI_TEXTURE,

	ALONE, DECOR,

	MINIATURE,

	SQUARE_SELECTION, GRID, PAINT, FILL, PLAYER_COLOR, ROTATE,

	CANCEL, SAVE,

	// PanColor
	SELECT_ALPHA,

	// ItemID
	ITEM_TAG, ITEM_ID, ITEM_COLOR, ITEM_SAVE, ITEM_CLEAR;
}
