package client.window.panels.editor;

public enum ActionEditor {
	EDITOR, EDIT_CUBE, EDIT_MULTI_CUBE, EDIT_MULTI_TEXTURE,

	ALONE, DECOR, GRID, MINIATURE, PAINT, FILL, PLAYER_COLOR, ROTATE, QUIT, SAVE,

	// No image
	VALID_COLOR, SELECT_ALPHA,

	// ItemID
	ITEM_NAME, ITEM_ID, ITEM_COLOR, ITEM_SAVE, ITEM_NEW, ITEM_CLEAR;
}
